#!/bin/bash

clean=
build=
dbg=

while getopts ":drcgh" opt; do
	case $opt in
		h)
			echo "This script runs desired build of the app."
			echo "Flags: "
			echo "-h : help"
			echo "-d : run debug version"
			echo -e "\t-g : when running debug version, start in gdb"
			echo "r : run release version"
			echo "c : make clean build before running"
			exit
			;;
		g)
			dbg=0
			;;
		c)
			clean=0
			;;
		r | d)
			if ! [ -z $build ]
			then
				echo "You can't run both builds at the same time!"
				exit
			fi
			if [ $opt == "r" ]
			then
				build="release"
			else
				build="debug"
			fi	  
			;;
		?)
			echo "$Unrecognized or missing flag!"
			exit
		;;
	esac	
done

if [ -e $build ]
then
	echo "You have to pick -r (release) or -d (debug). Use -h to get help!"
	exit
fi

if [ $clean ]
then
	make clean > /dev/null
fi


make "$build" > /dev/null

main="./build/$build/main"

if [ $dbg ]
then
	gdb $main
else
	$main
fi
	


